# Generated by Django 5.2.9 on 2026-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('token', models.CharField(max_length=255, verbose_name='Токен')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
