# Generated by Django 5.2.9 on 2026-06-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_primarytoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primarytoken',
            options={'verbose_name': 'Первичный токен', 'verbose_name_plural': 'Первичные токены'},
        ),
    ]
